# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Et in Arcadia Ego
email: kit@transneptune.net
description: > # this means to ignore newlines until "baseurl:"
  Arcadia is a game of manners, magic, and madness in the England of Jane
  Austen.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://arcadia.transneptunegames.com" # the base hostname & protocol for your site
enforce_ssl: "arcadia.transneptunegames.com"
twitter_username: wlonk
github_username: wlonk

# Build settings
markdown: kramdown
